### ISSUE TITLE
add example: Svelte

### ISSUE THREAD

**Issue by Bellisario** [socketsupply/socket-examples#60]
Would be great to see an actual working Svelte app.

**Comment by mribbons** [comment]
Hey @Bellisario, 
Have you tried
```
npx create-socket-app svelte 
```

Note that windows currently requires a workaround:
https://github.com/socketsupply/create-socket-app/issues/15#issuecomment-1445229567

**Comment by Bellisario** [comment]
Thanks @mribbons, works fine!

> Don't close the issue, we'll add a Svelte example :)

👍
