### ISSUE TITLE
I'm getting an error when I run the examples on windows

### ISSUE THREAD

**Issue by lamiazar** [socketsupply/socket-examples#66]
<img width="463" alt="Capture2" src="https://user-images.githubusercontent.com/79177582/227227132-42629021-db8d-444d-800b-9e5f9cf5afbd.PNG">

**Comment by lamiazar** [comment]
```
Run `npm audit` for details.
PS C:\Users\lamia\socket-examples\advanced\create-react-app> ssc build -r -o
• warning! $CXX env var not set, assuming defaults 29ms
• cleaned: C:\Users\lamia\socket-examples\advanced\create-react-app\dist\win 2ms
• preparing build for win 2ms
• using 'C:/Users/lamia/AppData/Roaming/npm/node_modules/@socketsupply/socket/node_modules/@socketsupply/socket-win32-x64\' as 'SOCKET_HOME' 0ms
• package prepared 59ms
• build failed, exiting with code -1 1716764ms
```

**Comment by wujekbizon** [comment]
Hey @chicoxyzzy , I've got same error alert : Unable to execute PUBLIC_URL=./npm run build

**Comment by chicoxyzzy** [comment]
Ah, that's a `create-react-app` example issue. I can fix it

**Comment by lamiazar** [comment]
@chicoxyzzy I opened this issue #69 and I think it's a duplicate.
Can I close #69 ?

**Comment by chicoxyzzy** [comment]
Yes, we can close it

**Comment by chicoxyzzy** [comment]
I've merged #70 cause it still works on macOS and Linux and works for some people (only me at the moment) on Windows, so it at least doesn't break anything. We need to check it on more machines. According to CRA docs it should just work.

**Comment by lamiazar** [comment]
It doesn't work for me as you know with old/ new version of `ssc`, I tried on my vm and a win machine

**Comment by chicoxyzzy** [comment]
@lamiazar @wujekbizon please try latest master. @mribbons fixes the issue in https://github.com/socketsupply/socket/pull/420

**Comment by lamiazar** [comment]
> @lamiazar @wujekbizon please try the latest master. @mribbons fixes the issue in https://github.com/socketsupply/socket/pull/420

it's working for me 
<img width="621" alt="Capture" src="https://github.com/socketsupply/socket-examples/assets/79177582/e6ff0d51-77a4-4889-8374-d668bee148e2">
@mribbons thank you!

**Comment by chicoxyzzy** [comment]
Awesome! Thank you @mribbons!
