### ISSUE TITLE
Getting errors when I run the examples(`socket-features`)

### ISSUE THREAD

**Issue by lamiazar** [socketsupply/socket-examples#76]
https://github.com/socketsupply/socket-examples/tree/master/todomvc `works` fine with the latest version:
<img width="832" alt="Screenshot 2023-09-26 at 1 47 35 PM" src="https://github.com/socketsupply/socket-examples/assets/79177582/88d29a1a-0062-4b4a-b9dc-be497914b96e">
```
lamia@lamias-Air ~ % ssc -v
0.4.0 (62e26b02)
Installation path: /Users/lamia/socket/build/npm/darwin/packages/@socketsupply/socket-darwin-arm64/
```

I'm getting some errors with : https://github.com/socketsupply/socket-examples/tree/master/socket-features 

```
lamia@lamias-Air extension % ssc build -r
• ERROR: [meta] bundle_name has invalid format :co.socketsupply.ios. +2ms
• Please use reverse DNS notation (https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleidentifier#discussion) +0ms
```

```
lamia@lamias-Air socket-features % cd multiple-windows 
lamia@lamias-Air multiple-windows % ssc build -r
• ERROR: [meta] bundle_identifier option is empty +1ms
```

```
lamia@lamias-Air socket-features % cd node-backend-bundled 
lamia@lamias-Air node-backend-bundled % ssc build -r
• ERROR: [meta] bundle_identifier option is empty +2ms
```

**Comment by bcomnes** [comment]
I fixed some of the more obvious errors in https://github.com/socketsupply/socket-examples/pull/77

**Comment by lamiazar** [comment]
- [ ] `extension`

<img width="1552" alt="Screenshot 2023-09-26 at 5 03 27 PM" src="https://github.com/socketsupply/socket-examples/assets/79177582/ba75008b-144c-4503-a9da-60e7b8e9c28b">

- [ ] `filesystem`

<img width="832" alt="Screenshot 2023-09-26 at 5 06 00 PM" src="https://github.com/socketsupply/socket-examples/assets/79177582/04ebf311-f0b8-4862-b0e2-2bef6d5a84eb">

- [ ] `multiple-windows`

<img width="832" alt="Screenshot 2023-09-26 at 5 06 56 PM" src="https://github.com/socketsupply/socket-examples/assets/79177582/ae6ac860-6cfc-41d7-9afe-fe99ed03cd86">

- [ ] `node-backend-bundled`

<img width="832" alt="Screenshot 2023-09-26 at 5 08 41 PM" src="https://github.com/socketsupply/socket-examples/assets/79177582/fe6171b1-86bb-4e6e-975b-c0fcc79ce423">

- [ ] `node-backend`
```
lamia@lamias-Air node-backend % ssc build -r   
• ERROR: [meta] bundle_identifier option is empty +0ms
```

**Comment by lamiazar** [comment]
- [ ] `node-backend` is working 
<img width="832" alt="Screenshot 2023-09-26 at 9 02 14 PM" src="https://github.com/socketsupply/socket-examples/assets/79177582/0cbe7adc-d7ef-4198-b77c-bdf92ca668ce">

**Comment by lamiazar** [comment]
All the examples in `socket-features` are working as expected.
