### ISSUE TITLE
What is the point of the Next.JS example?

### ISSUE THREAD

**Issue by lacymorrow** [socketsupply/socket-examples#81]
Don't get me wrong, I love Next.JS, however running Next.js without the API backend is... just a static React app. 

I've gone through the motions with this over the years adding Next to electron, then Nextron, is there some benefit to this example over a React App?

**Comment by bcomnes** [comment]
The point of the next app example is exactly that, a static MPA react app. Using next, one gets a pre-configured static MPA, webpack/JSX/TS config with a bunch of other goodies that next provides. The server components in Next have taken a spotlight lately as industry trends change, however the `export` option remains for now.
